name: Build an image with the signature

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    permissions:
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          # Suppose that your repository is located at https://github.com/<X>/<Y>, this value should be equal to X
          username: seccamp-2022-web
          password: ${{ github.token }}

      - name: install cosign
        uses: sigstore/cosign-installer@main

      - name: Prepare Dockerfile
        run: |
          echo "FROM alpine:3.10" > Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          # Suppose that your repository is located at https://github.com/<X>/<Y>, this value should be equal to ghcr.io/<X>/<random value>:latest
          tags: |
            ghcr.io/seccamp-2022-web/test-image-sasakiy84:latest
          platforms: linux/amd64
          push: true

      - name: sign the container image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign --force ghcr.io/seccamp-2022-web/test-image-sasakiy84:latest
      
      - name: Verify the container image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign verify ghcr.io/seccamp-2022-web/test-image-sasakiy84:latest